// What this machine can actually do, assembled at ask time.
//
// The AI is not told about Omarchy from memory -- it is handed the real
// command surface from `omarchy commands --json`, which is generated by the
// installed system and therefore cannot drift out of date the way a prompt
// full of remembered examples would. 281 usable routes is far too much
// context for a 3B local model, so the list is filtered against the phrase
// first and only the plausible handful is sent.

export interface OsCommand { route: string; summary: string; args?: string; group: string }

let cache: OsCommand[] | null = null

export async function loadOsCommands(): Promise<OsCommand[]> {
  if (cache) return cache
  try {
    const p = Bun.spawn(["omarchy", "commands", "--json"], { stdout: "pipe", stderr: "ignore" })
    const data = JSON.parse(await new Response(p.stdout).text())
    cache = (data.commands ?? [])
      // Hidden routes are not part of the supported surface, and anything
      // needing sudo is out of scope for a voice command by construction.
      .filter((c: any) => !c.hidden && !c.requires_sudo)
      .map((c: any) => ({
        route: String(c.route ?? ""),
        summary: String(c.summary ?? ""),
        args: c.args ? String(c.args) : undefined,
        group: String(c.group ?? ""),
      }))
    return cache!
  } catch {
    cache = []
    return cache
  }
}

const STOP = new Set(["the","a","an","to","for","on","of","my","me","please","and","in","at","is","it"])

// Lexical overlap alone cannot get from "dim" to "brightness" or "looks" to
// "theme", and the first version of this filter duly answered "dim the screen"
// with Plymouth boot themes. These are the bridges a word-match cannot build
// on its own. Only consulted when a LOCAL model is doing the planning; a
// hosted agent gets the whole map and does its own semantics.
const SYNONYMS: Record<string, string[]> = {
  dim: ["brightness"], darker: ["brightness"], brighter: ["brightness"],
  brightness: ["brightness"], screen: ["brightness", "display", "capture"],
  louder: ["audio", "volume"], quieter: ["audio", "volume"], volume: ["audio"],
  sound: ["audio"], mute: ["audio"], speaker: ["audio"], mic: ["audio"],
  looks: ["theme"], appearance: ["theme"], style: ["theme"], colours: ["theme"],
  colors: ["theme"], wallpaper: ["theme", "background"], background: ["theme"],
  song: ["launch", "webapp"], music: ["launch", "webapp"], video: ["launch", "webapp"],
  play: ["launch", "webapp"], watch: ["launch", "webapp"], youtube: ["launch", "webapp"],
  open: ["launch", "webapp"], app: ["launch"], install: ["install", "pkg"],
  screenshot: ["capture"], record: ["capture"], night: ["toggle"], wifi: ["network"],
  bluetooth: ["bluetooth"], battery: ["battery", "powerprofiles"],
}

function expand(ws: string[]): string[] {
  const out = new Set(ws)
  for (const w of ws) for (const s of SYNONYMS[w] ?? []) out.add(s)
  return [...out]
}

function words(s: string): string[] {
  return s.toLowerCase().replace(/[^a-z0-9\s-]/g, " ").split(/\s+/).filter(w => w && !STOP.has(w))
}

/**
 * Rank routes by word overlap with the phrase, so "make it louder" surfaces
 * the audio group and "dim the screen" surfaces brightness. Cheap, and good
 * enough: the model does the real judging, this only decides what it sees.
 */
export function relevantCommands(phrase: string, all: OsCommand[], limit = 40): OsCommand[] {
  const q = new Set(expand(words(phrase)))
  const scored = all.map(c => {
    const hay = new Set(words(`${c.route} ${c.summary} ${c.group}`))
    let score = 0
    for (const w of q) {
      if (hay.has(w)) score += 2
      else for (const h of hay) if (h.startsWith(w) || w.startsWith(h)) { score += 1; break }
    }
    return { c, score }
  })
  const hits = scored.filter(s => s.score > 0).sort((a, b) => b.score - a.score).map(s => s.c)
  // Always keep a spine of broadly useful groups so an unrelated phrase still
  // sees that volume, brightness, launching and themes exist.
  const spine = all.filter(c => ["audio", "brightness", "launch", "theme", "capture", "toggle"]
    .includes(c.group))
  const out: OsCommand[] = []
  const seen = new Set<string>()
  for (const c of [...hits, ...spine]) {
    if (seen.has(c.route)) continue
    seen.add(c.route)
    out.push(c)
    if (out.length >= limit) break
  }
  return out
}

/** Programs the model may use directly, verified present on this machine. */
export function availableTools(): string[] {
  const wanted = ["xdg-open", "mpv", "yt-dlp", "wpctl", "brightnessctl", "hyprctl",
                  "notify-send", "playerctl", "wl-copy", "grim"]
  return wanted.filter(t => Bun.which(t) !== null)
}
